spring:
  application:
    name: pasapalabra

  ai:
    openai:
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash

  jackson:
    datatype:
      enum:
        write-enums-to-lowercase: true

  threads:
    virtual:
      enabled: true

  mvc:
    problem-details:
      enabled: true
